In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_excel('historical_emissions_training.xlsx')
df

,Country,Data source,Sector,Gas,Unit,2015,2014,2013,2012,2011,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,Indonesia,CAIT,Total including LUCF,CO2,MtCO₂e,1574.76,1539.23,1250.27,1303.87,1285.69,...,849.42,907.96,1484.56,772.38,909.21,881.31,869.88,855.30,846.23,832.39
1,Malaysia,CAIT,Total including LUCF,CO2,MtCO₂e,124.54,135.37,109.59,91.92,92.13,...,222.59,233.95,214.34,206.21,197.88,191.20,185.40,183.09,177.54,170.40
2,Philippines,CAIT,Total including LUCF,CO2,MtCO₂e,116.10,106.84,100.23,90.49,86.90,...,74.84,77.33,77.73,69.90,64.21,53.90,49.87,46.14,42.77,43.25
3,Myanmar,CAIT,Total including LUCF,CO2,MtCO₂e,128.25,124.63,121.56,118.38,114.79,...,150.15,149.01,147.66,148.08,148.94,147.62,146.79,146.26,146.10,146.17
4,Vietnam,CAIT,Total including LUCF,CO2,MtCO₂e,186.54,146.44,132.72,124.61,126.39,...,-27.25,-27.51,-32.40,-38.30,-41.95,-45.54,-48.04,-52.98,-53.98,-53.88
5,Singapore,CAIT,Total including LUCF,CO2,MtCO₂e,45.45,44.41,43.87,43.64,44.72,...,38.42,37.94,39.45,39.81,38.83,39.19,37.32,32.13,31.24,29.67
6,Laos,CAIT,Total including LUCF,CO2,MtCO₂e,17.32,13.09,12.58,11.94,11.71,...,11.35,11.32,11.29,11.25,11.17,11.14,11.11,11.10,11.05,11.02
7,Brunei,CAIT,Total including LUCF,CO2,MtCO₂e,6.35,7.37,7.36,7.48,7.36,...,5.50,8.74,6.58,6.07,6.03,5.66,5.38,5.10,4.90,5.43
8,Cambodia,CAIT,Total including LUCF,CO2,MtCO₂e,73.51,71.55,70.50,70.35,70.11,...,6.08,6.11,5.87,5.78,5.68,5.64,5.55,5.52,5.47,5.43
9,Thailand,CAIT,Total including LUCF,CO2,MtCO₂e,263.34,259.38,262.72,252.33,234.88,...,174.18,167.52,188.50,185.34,166.83,148.39,134.23,119.61,109.85,100.74

In [3]:
df.iloc[0,6:9]

2014    1539.23
2013    1250.27
2012    1303.87
Name: 0, dtype: object

In [71]:
n=6
data=[]
fitur=[]
label=[]
# tuple=()
for i in range(0,len(df.columns)-9):
    data=df.iloc[0,n-1:n+3].values
    # data2=df.iloc[0,n+3:n+4].values
    n+=1
    # x=tuple(data)
    # y=tuple(data2)
    fitur.append(data)
    # label.append(data2)

TypeError: only size-1 arrays can be converted to Python scalars

In [70]:
print(fitur)

[array([1574.76, 1539.23, 1250.27, 1303.87], dtype=object), array([1539.23, 1250.27, 1303.87, 1285.69], dtype=object), array([1250.27, 1303.87, 1285.69, 773.92], dtype=object), array([1303.87, 1285.69, 773.92, 1036.71], dtype=object), array([1285.69, 773.92, 1036.71, 731.76], dtype=object), array([773.92, 1036.71, 731.76, 738.57], dtype=object), array([1036.71, 731.76, 738.57, 1152.83], dtype=object), array([731.76, 738.57, 1152.83, 829.93], dtype=object), array([738.57, 1152.83, 829.93, 1031.49], dtype=object), array([1152.83, 829.93, 1031.49, 761.93], dtype=object), array([829.93, 1031.49, 761.93, 1001.39], dtype=object), array([1031.49, 761.93, 1001.39, 631.16], dtype=object), array([761.93, 1001.39, 631.16, 795.62], dtype=object), array([1001.39, 631.16, 795.62, 849.42], dtype=object), array([631.16, 795.62, 849.42, 907.96], dtype=object), array([795.62, 849.42, 907.96, 1484.56], dtype=object), array([849.42, 907.96, 1484.56, 772.38], dtype=object), array([907.96, 1484.56, 772.38, 909.21], dtype=object), array([1484.56, 772.38, 909.21, 881.31], dtype=object), array([772.38, 909.21, 881.31, 869.88], dtype=object), array([909.21, 881.31, 869.88, 855.3], dtype=object), array([881.31, 869.88, 855.3, 846.23], dtype=object)]

In [67]:
lbl=np.array(df.iloc[0,9:31].values)
print(lbl)

[1285.69 773.92 1036.71 731.76 738.57 1152.83 829.93 1031.49 761.93
 1001.39 631.16 795.62 849.42 907.96 1484.56 772.38 909.21 881.31 869.88
 855.3 846.23 832.39]

In [68]:
gnb = GaussianNB()
gnb.fit(fitur, lbl)

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)

ValueError: Unknown label type: (array([631.16, 731.76, 738.57, 761.93, 772.38, 773.92, 795.62, 829.93,
       832.39, 846.23, 849.42, 855.3, 869.88, 881.31, 907.96, 909.21,
       1001.39, 1031.49, 1036.71, 1152.83, 1285.69, 1484.56], dtype=object),)